In [6]:
import pandas as pd
import numpy as np

crime_seoul = pd.read_csv("crime_Seoul2.csv", encoding='utf-8',  
                         index_col=0)
#crime_seoul['구별']
crime_seoul
crime_pivot = pd.pivot_table(crime_seoul, index='구별', aggfunc=np.sum)
crime_pivot.head()

# 컬럼 추가(5)
# 강간검거율, 강도검거율, 살인검거율, 절도검거율, 폭력검거율
# 강도거거율 = 강도 검거 / 강도 발생 * 100
crime_pivot['강간검거율'] = crime_pivot['강간 검거'] / crime_pivot['강간 발생'] * 100
crime_pivot['강도검거율'] = crime_pivot['강도 검거'] / crime_pivot['강도 발생'] * 100
crime_pivot['살인검거율'] = crime_pivot['살인 검거'] / crime_pivot['살인 발생'] * 100
crime_pivot['절도검거율'] = crime_pivot['절도 검거'] / crime_pivot['절도 발생'] * 100
crime_pivot['폭력검거율'] = crime_pivot['폭력 검거'] / crime_pivot['폭력 발생'] * 100

In [7]:
del crime_pivot['강간 검거']
del crime_pivot['강도 검거']
del crime_pivot['살인 검거']
del crime_pivot['절도 검거']
del crime_pivot['폭력 검거']
crime_pivot.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,185.714286,100.000000,42.200925,83.047619

In [9]:
crime_pivot.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,185.714286,100.000000,42.200925,83.047619

In [33]:
cols = ['강간검거율', '강도검거율', '살인검거율', '절도검거율', '폭력검거율']
for s in cols:
    crime_pivot.loc[crime_pivot[s] > 100, s] = 100
crime_pivot.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,100.000000,100.000000,42.200925,83.047619

In [1]:
from sklearn.preprocessing import MinMaxScaler

a = [[1], [10],[9]]

#1,10,9를 0과 1사이에서 표현 
s = MinMaxScaler(feature_range=(0,1))

a = s.fit_transform(a)
a

[[1], [10], [9]]

array([[0.        ],
       [1.        ],
       [0.88888889]])

In [3]:
crime_pivot.rename(columns={
    '강간 발생' : '강간',
    '강도 발생' : '강도',
    '살인 발생' : '살인',
    '절도 발생' : '절도',
    '폭력 발생' : '폭력'
}, inplace=True)

NameError: name 'crime_pivot' is not defined

In [2]:
crime_pivot.head()

NameError: name 'crime_pivot' is not defined

In [64]:
from sklearn.preprocessing import MinMaxScaler
cols2 = ['강간','강도','살인','절도','폭력']
x = crime_pivot[cols2].values
s = MinMaxScaler()
s2 = s.fit_transform(x.astype(float))
#crime_pivot.index
crime_data = pd.DataFrame(s2, columns=cols2, index=crime_pivot.index)
#print(crime_data.head())
#print(crime_pivot.head())
crime_pivot[cols2] = crime_data[cols2]

In [65]:
crime_pivot.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619