In [7]:
import pandas as pd
import numpy as np

crime_seoul = pd.read_csv("crime_Seoul2.csv", encoding='utf-8',  
                         index_col=0)
#crime_seoul['구별']
crime_seoul
crime_pivot = pd.pivot_table(crime_seoul, index='구별', aggfunc=np.sum)
crime_pivot.head()

# 컬럼 추가(5)
# 강간검거율, 강도검거율, 살인검거율, 절도검거율, 폭력검거율
# 강도거거율 = 강도 검거 / 강도 발생 * 100
crime_pivot['강간검거율'] = crime_pivot['강간 검거'] / crime_pivot['강간 발생'] * 100
crime_pivot['강도검거율'] = crime_pivot['강도 검거'] / crime_pivot['강도 발생'] * 100
crime_pivot['살인검거율'] = crime_pivot['살인 검거'] / crime_pivot['살인 발생'] * 100
crime_pivot['절도검거율'] = crime_pivot['절도 검거'] / crime_pivot['절도 발생'] * 100
crime_pivot['폭력검거율'] = crime_pivot['폭력 검거'] / crime_pivot['폭력 발생'] * 100

crime_pivot

,강간 검거,강간 발생,강도 검거,강도 발생,살인 검거,살인 발생,절도 검거,절도 발생,폭력 검거,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,,,,,
강남구,349,449,18,21,10,13,1650,3850,3705,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,123,156,8,6,3,4,789,2366,2248,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,126,153,13,14,8,7,618,1434,2348,2649,82.352941,92.857143,114.285714,43.096234,88.637222
관악구,221,320,14,12,8,9,827,2706,2642,3298,69.062500,116.666667,88.888889,30.561715,80.109157
광진구,220,240,26,14,4,4,1277,3026,2180,2625,91.666667,185.714286,100.000000,42.200925,83.047619
구로구,164,281,11,15,6,8,889,2335,2432,3007,58.362989,73.333333,75.000000,38.072805,80.877951
금천구,122,151,6,6,4,3,888,1567,1776,2054,80.794702,100.000000,133.333333,56.668794,86.465433
노원구,121,197,7,7,10,10,801,2193,2329,2723,61.421320,100.000000,100.000000,36.525308,85.530665
도봉구,106,102,10,9,3,3,478,1063,1303,1487,103.921569,111.111111,100.000000,44.967074,87.626093
동대문구,146,173,13,13,5,5,814,1981,2227,2548,84.393064,100.000000,100.000000,41.090358,87.401884
동작구,139,285,5,9,5,5,661,1865,1587,1910,48.771930,55.555556,100.000000,35.442359,83.089005
마포구,247,294,10,14,8,8,813,2555,2519,2983,84.013605,71.428571,100.000000,31.819961,84.445189
서대문구,124,154,4,5,2,2,738,1812,1711,2056,80.519481,80.000000,100.000000,40.728477,83.219844
서초구,249,393,6,9,6,8,1091,2635,2098,2399,63.358779,66.666667,75.000000,41.404175,87.453105
성동구,119,126,8,9,4,4,597,1607,1395,1612,94.444444,88.888889,100.000000,37.149969,86.538462
성북구,124,150,4,5,5,5,741,1785,1855,2209,82.666667,80.000000,100.000000,41.512605,83.974649
송파구,178,220,10,13,10,11,1129,3239,2786,3295,80.909091,76.923077,90.909091,34.856437,84.552352
양천구,296,382,16,19,13,10,1932,3986,4748,5716,77.486911,84.210526,130.000000,48.469644,83.065080
영등포구,183,295,20,22,12,14,978,2964,2961,3572,62.033898,90.909091,85.714286,32.995951,82.894737
용산구,173,194,14,14,5,5,587,1557,1704,2050,89.175258,100.000000,100.000000,37.700706,83.121951
은평구,141,166,6,9,3,3,711,1914,2306,2653,84.939759,66.666667,100.000000,37.147335,86.920467
종로구,161,211,9,11,5,6,837,2184,1931,2293,76.303318,81.818182,83.333333,38.324176,84.212822
중구,111,170,6,9,2,3,859,2548,1964,2224,65.294118,66.666667,66.666667,33.712716,88.309353
중랑구,148,187,9,11,12,13,829,2135,2407,2847,79.144385,81.818182,92.307692,38.829040,84.545135

In [5]:
del crime_pivot['강간 검거']
del crime_pivot['강도 검거']
del crime_pivot['살인 검거']
del crime_pivot['절도 검거']
del crime_pivot['폭력 검거']
crime_pivot.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,185.714286,100.000000,42.200925,83.047619

In [23]:
crime_pivot.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,185.714286,100.000000,42.200925,83.047619

In [33]:
cols = ['강간검거율', '강도검거율', '살인검거율', '절도검거율', '폭력검거율']
for s in cols:
    crime_pivot.loc[crime_pivot[s] > 100, s] = 100
crime_pivot.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,100.000000,100.000000,42.200925,83.047619

In [37]:
from sklearn.preprocessing import MinMaxScaler
a = [[1], [10],[9]]
s = MinMaxScaler(feature_range=(0,1))
a = s.fit_transform(a)
a

array([[0.        ],
       [1.        ],
       [0.88888889]])

In [42]:
crime_pivot.rename(columns={
    '강간 발생' : '강간',
    '강도 발생' : '강도',
    '살인 발생' : '살인',
    '절도 발생' : '절도',
    '폭력 발생' : '폭력'
}, inplace=True)

In [44]:
crime_pivot.head()

In [64]:
from sklearn.preprocessing import MinMaxScaler
cols2 = ['강간','강도','살인','절도','폭력']
x = crime_pivot[cols2].values
s = MinMaxScaler()
s2 = s.fit_transform(x.astype(float))
#crime_pivot.index
crime_data = pd.DataFrame(s2, columns=cols2, index=crime_pivot.index)
#print(crime_data.head())
#print(crime_pivot.head())
crime_pivot[cols2] = crime_data[cols2]

In [65]:
crime_pivot.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619