In [50]:
import pandas as pd
import numpy as np

cctv_seoul = pd.read_csv("Data/CCTV_Seoul.csv", encoding = "utf-8")
cctv_seoul.head()

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [51]:
cctv_seoul.columns
cctv_seoul.columns[0]
cctv_seoul.rename(columns = {cctv_seoul.columns[0]:'구별'}, inplace = True)
cctv_seoul.head()

    구별    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [73]:
pop_seoul = pd.read_excel("Data/population_Seoul.xls", encoding='utf-8'
                         , header = 2
                         , usecols = 'B,D,G,J,N'
                         )

print(pop_seoul.columns[0])
pop_seoul.rename(columns = {pop_seoul.columns[0] : '구별' 
                        ,pop_seoul.columns[1] : '인구'
                        ,pop_seoul.columns[2] : '한국인'
                        ,pop_seoul.columns[3] : '외국인'
                        ,pop_seoul.columns[4] : '고령자'
                           }, inplace = True )

pop_seoul.drop([0], inplace=True)
#pop_seoul.sort_index(axis = 0)
#pop_seoul.sort_values(by='고령자',ascending=False)
#pop_seoul.sort_values(by=['인구','고령자'],ascending=[False,True])


#pop_seoul.drop([26], inplace=True)

자치구

In [74]:
cctv_seoul['최근증가율'] = (cctv_seoul['2016년'] + cctv_seoul['2015년'] + 
                       cctv_seoul['2014년'] ) / cctv_seoul['2013년도 이전'] * 100 
cctv_seoul.head()

    구별    소계  2013년도 이전  2014년  2015년  2016년       최근증가율
0  강남구  2780       1292    430    584    932  150.619195
1  강동구   773        379     99    155    377  166.490765
2  강북구   748        369    120    138    204  125.203252
3  강서구   884        388    258    184     81  134.793814
4  관악구  1496        846    260    390    613  149.290780

In [89]:
pop_seoul['구별'].unique()
pop_seoul['구별'].isnull()
pop_seoul[pop_seoul['구별'].isnull()].index

Int64Index([26], dtype='int64')

In [93]:
pop_seoul['외국인비율'] = pop_seoul['외국인']/ pop_seoul['인구'] * 100
pop_seoul['고령자비율'] = pop_seoul['고령자']/ pop_seoul['인구'] * 100

pd.merge(pop_seoul, cctv_seoul, on = ['구별'])
#보고싶은것만 보려면?

,구별,인구,한국인,외국인,고령자,외국인비율,고령자비율,소계,2013년도 이전,2014년,2015년,2016년,최근증가율
0,종로구,162820.0,153589.0,9231.0,25425.0,5.669451,15.615404,1002,464,314,211,630,248.922414
1,중구,133240.0,124312.0,8928.0,20764.0,6.700690,15.583909,671,413,190,72,348,147.699758
2,용산구,244203.0,229456.0,14747.0,36231.0,6.038828,14.836427,1624,1368,218,112,398,53.216374
3,성동구,311244.0,303380.0,7864.0,39997.0,2.526635,12.850689,1062,730,91,241,265,81.780822
4,광진구,372164.0,357211.0,14953.0,42214.0,4.017852,11.342849,707,573,78,53,174,53.228621
5,동대문구,369496.0,354079.0,15417.0,54173.0,4.172440,14.661322,1294,1070,23,198,579,74.766355
6,중랑구,414503.0,409882.0,4621.0,56774.0,1.114829,13.696885,660,509,121,177,109,79.960707
7,성북구,461260.0,449773.0,11487.0,64692.0,2.490353,14.025062,1464,1009,78,360,204,63.627354
8,강북구,330192.0,326686.0,3506.0,54813.0,1.061806,16.600342,748,369,120,138,204,125.203252
9,도봉구,348646.0,346629.0,2017.0,51312.0,0.578524,14.717507,485,238,159,42,386,246.638655
10,노원구,569384.0,565565.0,3819.0,71941.0,0.670725,12.634883,1265,542,57,451,516,188.929889
11,은평구,494388.0,489943.0,4445.0,72334.0,0.899091,14.631019,1873,1138,224,278,468,85.237258
12,서대문구,327163.0,314982.0,12181.0,48161.0,3.723221,14.720797,962,844,50,68,292,48.578199
13,마포구,389649.0,378566.0,11083.0,48765.0,2.844355,12.515110,574,314,118,169,379,212.101911
14,양천구,479978.0,475949.0,4029.0,52975.0,0.839413,11.036964,2034,1843,142,30,467,34.671731
15,강서구,603772.0,597248.0,6524.0,72548.0,1.080540,12.015794,884,388,258,184,81,134.793814
16,구로구,447874.0,416487.0,31387.0,56833.0,7.007998,12.689506,1561,1142,173,246,323,64.973730
17,금천구,255082.0,236353.0,18729.0,32970.0,7.342345,12.925255,1015,674,51,269,354,100.000000
18,영등포구,402985.0,368072.0,34913.0,52413.0,8.663598,13.006191,904,495,214,195,373,157.979798
19,동작구,412520.0,400456.0,12064.0,56013.0,2.924464,13.578251,1091,544,341,103,314,139.338235
20,관악구,525515.0,507203.0,18312.0,68082.0,3.484582,12.955291,1496,846,260,390,613,149.290780
21,서초구,450310.0,445994.0,4316.0,51733.0,0.958451,11.488308,1930,1406,157,336,398,63.371266
22,강남구,570500.0,565550.0,4950.0,63167.0,0.867660,11.072217,2780,1292,430,584,932,150.619195
23,송파구,667483.0,660584.0,6899.0,72506.0,1.033584,10.862599,618,529,21,68,463,104.347826
24,강동구,453233.0,449019.0,4214.0,54622.0,0.929765,12.051638,773,379,99,155,377,166.490765